/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_service_app_db_Data */

#ifndef _Included_android_service_app_db_Data
#define _Included_android_service_app_db_Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
